language: ruby
rvm:
- 1.9.3
- 2.0.0
- 2.1.1
before_install: 'echo ''gem: --no-ri --no-rdoc'' > ~/.gemrc'
script: bundle exec rake test
branches:
  only:
  - master
notifications:
  hipchat:
    rooms:
      secure: chCwvs4r/T0iZKrHtvr6eYsM4QNPWUo90lxg6U/pWvbPGr3dWTUsAfCCrUAErY6kdh+bsm+l4dyZa0FdWnBrgSGAmUlD1myXot0thIyDtrFbHNb6wX4jv+UWi70P55zqPY/wrvrtgV0GZTPIJvbnC2XUjOaCreLFePCQmFI0pbI=
env:
  global:
    secure: ox4PooiCwoyJanrirdmxMCRxp3q+k42N2sbGEdUR4FCVZKeXZynRg6Gd/7DA1CCg2gvQvrPyfs1sKaMAYPxwbv5O32k8bFXD4Ju5OTIqrOK/Rgu1MW/QDeUX7/Z10M3APjWMGDDl1JnEKC82C1rnRYunozjE0Zq6+Hzvbdei8Oc=
