language: ruby
rvm:
- 1.9.3
- 2.0.0
- 2.1.1
before_install: 'echo ''gem: --no-ri --no-rdoc'' > ~/.gemrc'
script: bundle exec rake test
branches:
  only:
  - master
notifications:
  hipchat:
    rooms:
      secure: chCwvs4r/T0iZKrHtvr6eYsM4QNPWUo90lxg6U/pWvbPGr3dWTUsAfCCrUAErY6kdh+bsm+l4dyZa0FdWnBrgSGAmUlD1myXot0thIyDtrFbHNb6wX4jv+UWi70P55zqPY/wrvrtgV0GZTPIJvbnC2XUjOaCreLFePCQmFI0pbI=
